--  Name : Parth Sarkhelia (AU1841045)
--  Assignment 01 :	Inventory Management  (Q02)



DROP TABLE STOCK;
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;
DROP TABLE SUPPLIER;
DROP TABLE BRAND;

CREATE TABLE BRAND (
    BRAND_ID INT ,
    BRAND_NAME VARCHAR(50),
    CONSTRAINT PK_BRAND PRIMARY KEY (BRAND_ID)
);

CREATE TABLE SUPPLIER (
    SUPPLIER_ID INT,
    SUPPLIER_NAME VARCHAR(50) NOT NULL,
    SUPPLIER_ADDRESS VARCHAR(100) NOT NULL,
    SUPPLIER_EMAIL VARCHAR(50),
    SUPPLIER_PHONE VARCHAR(15) NOT NULL,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE CATEGORY (
    CATEGORY_ID INT,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    BRAND_ID INT,
    CATEGORY_ID INT,
    PRODUCT_PRICE INT NOT NULL,
    SUPPLIER_ID INT,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
    CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_PRODUCT_BRAND_ID FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
);

CREATE TABLE stock (
    PRODUCT_ID INT,
    PRODUCT_QUANTITY INT,
    CONSTRAINT PK_STOCK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_STOCK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) 
);

--  1.	Increase the size of product_name field by 5 characters.

ALTER TABLE PRODUCT MODIFY PRODUCT_NAME VARCHAR(55);
DESC PRODUCT;


-- 2.	Add constraint which won’t allow user to enter product_quantity less than zero in Inventory.

ALTER TABLE STOCK MODIFY PRODUCT_QUANTITY CHECK (PRODUCT_QUANTITY > 0);
DESC STOCK;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='STOCK';


-- 3.	Add a column update_date in table Inventory.

ALTER TABLE STOCK ADD UPDATE_DATE DATE;
DESC STOCK;


-- 4.	Add  a constraint in brand table for  brand_name to be unique  .

ALTER TABLE BRAND MODIFY BRAND_NAME UNIQUE;
DESC BRAND;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='BRAND';


-- 5.	Drop foreign key constraint for product_brand field of Product table.

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='PRODUCT';
ALTER TABLE PRODUCT DROP CONSTRAINT FK_PRODUCT_BRAND_ID ;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='PRODUCT';


-- 6.	Rename column product_supplier_id of product as supplier_id.

ALTER TABLE PRODUCT RENAME COLUMN SUPPLIER_ID TO PRODUCT_SUPPLIER_ID;
DESC PRODUCT;
ALTER TABLE PRODUCT RENAME COLUMN PRODUCT_SUPPLIER_ID TO SUPPLIER_ID;
DESC PRODUCT;


-- 7.	Add a field “supplier_status” having valid values as “active” or “inactive” in supplier table.

ALTER TABLE SUPPLIER ADD SUPPLIER_STATUS VARCHAR(10);
ALTER TABLE SUPPLIER MODIFY SUPPLIER_STATUS CHECK (SUPPLIER_STATUS = 'ACTIVE' OR SUPPLIER_STATUS = 'INACTIVE');
DESC SUPPLIER;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE,SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='SUPPLIER';


-- 8.	Add a constraint for category_type  either “laptop” or “mobile”.

ALTER TABLE CATEGORY MODIFY CATEGORY_NAME CHECK (CATEGORY_NAME = 'LAPTOP' OR CATEGORY_NAME = 'MOBILE');
DESC CATEGORY;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CATEGORY';


-- 9.	Drop primary key constraint from Inventory table.

ALTER TABLE STOCK DROP CONSTRAINT PK_STOCK;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'STOCK';
DESC STOCK;


-- 10.	Rename table Stock as Inventory.

RENAME STOCK TO INVENTORY;
DESC INVENTORY;


